#!/bin/bash



LD_LIBRARY_PATH+=./BUTool/lib/:./plugins/BUTool-IPBUS-Helpers/lib/:./plugins/ApolloSM_plugin/lib/ ./BUTool/bin/tool/BUTool.exe -l plugins/ApolloSM_plugin/lib/libBUTool_ApolloSMDevice.so "bash -s ${xx} ${link} ${node} ${binx} ${biny} ${max_prescale} ${time}" <<-EOL
	add_device APOLLOSM /opt/address_table/connections_SM_CM.xml SM_CM
	status 3 FIRMWARE
        es $4 $5 $6 $2 $3 es_$4_$5_$6_$2_apollo$1_$7.txt 
	exit
EOL
